###################################
## General Settings

## These settings are standard Jekyll Settings, check the Jekyll docs for help

## Preprocessor settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM

## Jekyll Serve
port: 4000

## Output
siteurl:                    ## Optional 
baseurl: /project-log
destination: docs


title: ARlebnispfade Projekt Log
keywords: jekyll, ARlebnispfade OBK 
author: Christian Noss
description: Hier schreiben wir ein bisschen was über das Projekt, dokumentieren Entscheidungen, sammeln Forschungsfragen und so weiter.
language: de
styles: assets/css/arlebnispfade.css
favicon: assets/images/favicon.ico

## Generates Style Guide Shell Styles
## Enable to change the style guide shell stylesheet.
#sass: 
#  sass_dir: styleguide/_scss
#  style: :compressed


## Generates Pattern Styles
## Disable to prevent pattern styles from being generated.
sass:
  sass_dir: assets/_scss 
  style: compressed

collections:
  news:
    output: false